spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/big_event
    username: root
    password: 123456
  data:
    redis:
      host: redis
      port: 6379
server:
  port: 8642
  servlet:
    context-path: /big-event

mybatis:
  configuration:
    map-underscore-to-camel-case: true

oss:
  accessKey:
  secretKey:
  bucket:
  domain:
